name: 'jest tests'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: NODE_OPTIONS=--experimental-vm-modules npx jest
